#!/usr/bin/env python3
"""
Recomputes plan.md's completion percentage from its own checkbox items and rewrites
the auto-generated progress block near the top of the file -- so "how done is this"
is always a real count of `- [x]`/`- [ ]`/`- [~]` lines, never a stale hand-typed
number someone forgot to update after checking a box.

Counting rule: `- [x]` = 1 point, `- [ ]` = 0 points, `- [~]` (partial -- used for
genuinely half-finished items like Phase 10's on-robot inference loop skeleton) =
0.5 points. Only top-level checkbox lines under a `## Phase N` heading are counted;
plain bullets (e.g. the "Open decisions this plan still can't make for you" section)
are not checklist items and are correctly ignored.

Idempotent: running this twice in a row with no other changes to plan.md produces
byte-identical output the second time -- safe to run from a pre-commit hook on every
commit (see hooks/pre-commit) without creating no-op diffs.

Run directly: python update_plan_progress.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PLAN_PATH = Path(__file__).parent / "plan.md"

CHECKBOX_RE = re.compile(r"^- \[([ x~])\]")
PHASE_RE = re.compile(r"^## (Phase \d+.*)$")

START_MARKER = "<!-- PROGRESS:START -->"
END_MARKER = "<!-- PROGRESS:END -->"

POINTS = {"x": 1.0, "~": 0.5, " ": 0.0}


def compute_progress(text: str) -> tuple[float, int, list[tuple[str, float, int]]]:
    """Returns (total_points, total_items, [(phase_name, phase_points, phase_items), ...])."""
    current_phase = None
    per_phase: dict[str, list[float]] = {}
    order: list[str] = []

    for line in text.splitlines():
        phase_match = PHASE_RE.match(line)
        if phase_match:
            current_phase = phase_match.group(1)
            if current_phase not in per_phase:
                per_phase[current_phase] = []
                order.append(current_phase)
            continue
        box_match = CHECKBOX_RE.match(line)
        if box_match and current_phase is not None:
            per_phase[current_phase].append(POINTS[box_match.group(1)])

    total_points = sum(p for pts in per_phase.values() for p in pts)
    total_items = sum(len(pts) for pts in per_phase.values())
    phase_rows = [(name, sum(per_phase[name]), len(per_phase[name])) for name in order]
    return total_points, total_items, phase_rows


def render_bar(frac: float, width: int = 24) -> str:
    filled = round(frac * width)
    return "#" * filled + "-" * (width - filled)


def build_block(total_points: float, total_items: int, phase_rows: list[tuple[str, float, int]]) -> str:
    pct = (total_points / total_items * 100.0) if total_items else 0.0
    lines = [START_MARKER, "## Progress"]
    lines.append("")
    lines.append(f"**`{render_bar(pct / 100.0)}` {pct:.1f}%** ({total_points:g} / {total_items} items)")
    lines.append("")
    lines.append("| Phase | Done |")
    lines.append("|---|---|")
    for name, pts, n in phase_rows:
        phase_pct = (pts / n * 100.0) if n else 0.0
        lines.append(f"| {name} | {pts:g}/{n} ({phase_pct:.0f}%) |")
    lines.append("")
    lines.append(
        "_Auto-generated by `update_plan_progress.py` from this file's own `- [x]`/`- [ ]`/`- [~]` "
        "checkboxes -- do not hand-edit this block, it's overwritten on every commit "
        "(`hooks/pre-commit`) and by running the script directly._"
    )
    lines.append(END_MARKER)
    return "\n".join(lines)


def update_plan_md() -> bool:
    """Returns True if plan.md's content changed (caller may want to re-stage it)."""
    text = PLAN_PATH.read_text(encoding="utf-8")
    total_points, total_items, phase_rows = compute_progress(text)
    block = build_block(total_points, total_items, phase_rows)

    if START_MARKER in text and END_MARKER in text:
        pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
        new_text = pattern.sub(block, text, count=1)
    else:
        # First run: insert right after the H1 title line, before everything else,
        # so the progress summary is the first thing visible when opening the file.
        lines = text.splitlines(keepends=True)
        insert_at = 1 if lines and lines[0].startswith("# ") else 0
        new_text = "".join(lines[:insert_at]) + "\n" + block + "\n\n" + "".join(lines[insert_at:])

    changed = new_text != text
    if changed:
        PLAN_PATH.write_text(new_text, encoding="utf-8")
    return changed


if __name__ == "__main__":
    changed = update_plan_md()
    total_points, total_items, _ = compute_progress(PLAN_PATH.read_text(encoding="utf-8"))
    pct = (total_points / total_items * 100.0) if total_items else 0.0
    print(f"plan.md progress: {pct:.1f}% ({total_points:g}/{total_items}) -- {'updated' if changed else 'already up to date'}")
    sys.exit(0)
